CREATE DATABASE USER COLLATE 'utf8_general_ci'

CREATE TABLE USERS (
    ID INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(50)
);

-- PROCEDIMIENTO ALMACENADO

BEGIN
	INSERT INTO USERS ( NAME ) VALUES ( _NAME );
END;

BEGIN
	SELECT ID, NAME FROM USERS;
END;

-- SCRIPTS 

-- INSERTAR
CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN INSERT INTO USERS ( NAME ) VALUES ( _NAME ); END;
-- MOSTRAR TODO
CREATE PROCEDURE `spFindAllUsers`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT ID, NAME FROM USERS; END;

-- LLAMADO DE DEL SCRIPT
CALL spInsertUser('DEIMER');
CALL spFindAllUsers();

spInsertUser
spUpdateUser
spDeleteUser
spFindUser
spFindAllUsers