CREATE DATABASE USER COLLATE 'utf8_general_ci';

CREATE TABLE USERS (ID INT(4) PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME VARCHAR(50));

-- PROCEDIMIENTOS ALMACENADOS
-- INSERTAR
BEGIN
	INSERT INTO USERS ( NAME ) VALUES ( _NAME );
END;
-- MOSTRAR UNO
BEGIN
	SELECT ID, NAME FROM USERS WHERE ID = _ID;
END;
-- MOSTRAR TODO
BEGIN
	SELECT ID, NAME FROM USERS;
END;
-- ACTUALIZAR
BEGIN
	UPDATE USERS SET NAME = _NAME WHERE ID = _ID;
END;
-- BORRAR
BEGIN
	DELETE FROM USERS WHERE ID = _ID;
END 

-- SCRIPTS 

-- INSERTAR
CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN INSERT INTO USERS ( NAME ) VALUES ( _NAME ); END;
-- MOSTRAR UNO

-- MOSTRAR TODO
CREATE PROCEDURE `spFindAllUsers`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT ID, NAME FROM USERS; END;
-- ACTUALIZAR
CREATE PROCEDURE `spUpdateUser`(IN `_ID` INT(5), IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN UPDATE USERS SET NAME = _NAME WHERE ID = _ID; END;
-- BORRAR
CREATE PROCEDURE `spDeleteUser`(IN `ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN DELETE FROM USERS WHERE ID = _ID; END

-- LLAMADO DE DEL SCRIPT
CALL spInsertUser('DEIMER');
CALL spFindAllUsers();
CALL spFindUser(1);
CALL spUpdateUser(1);
CALL spDeleteUser(2);


spInsertUser
spUpdateUser
spDeleteUser
spFindUser
spFindAllUsers